### ISSUE TITLE
Parole con spazio "rompono" plugin e config

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWChatControl#1]
## Expected Behavior
Il plugin dovrebbe accettare il ban di frasi o più parole in una stessa frase.

## Actual Behavior
Il plugin entra in errore e "rompe" il config.

## Steps to Reproduce the Problem

  1. fare nel server "fwcc word ban parola parola

## Specifications

  - Version: 1.16.4
  - Platform: paper
  - Subsystem: Paper version git-Paper-345 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

## Details

15:34:27 INFO]: config.yml has been loaded
fwcc word ban dio porco
[15:34:32 INFO]: config.yml has been found
[15:34:32 ERROR]: Cannot load plugins/FWChatControl/config.yml
org.bukkit.configuration.InvalidConfigurationException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.stream.ReferencePipeline$3
 in 'string', line 13, column 14:
    bannedWords: !!java.util.stream.ReferencePipe ... 
                 ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:186) ~[patched_1.16.4.jar:git-Paper-345]
        at it.forgottenworld.fwchatcontrol.config.Config.loadConfig(Config.java:101) ~[?:?]
        at it.forgottenworld.fwchatcontrol.config.Config.<init>(Config.java:43) ~[?:?]
        at it.forgottenworld.fwchatcontrol.config.Config.<init>(Config.java:29) ~[?:?]
        at it.forgottenworld.fwchatcontrol.FWChatControl.saveConfig(FWChatControl.java:53) ~[?:?]
        at it.forgottenworld.fwchatcontrol.command.AdminCommand.banWord(AdminCommand.java:63) ~[?:?]
        at it.forgottenworld.fwchatcontrol.command.AdminCommand.onCommand(AdminCommand.java:33) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.4.jar:git-Paper-345]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.4.jar:git-Paper-345]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.4.jar:git-Paper-345]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.4.jar:git-Paper-345]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-345]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-345]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag tag:yaml.org,2002:java.util.stream.ReferencePipeline$3
 in 'string', line 13, column 14:
    bannedWords: !!java.util.stream.ReferencePipe ... 
                 ^

        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:576) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:479) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:190) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:460) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:556) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472) ~[patched_1.16.4.jar:git-Paper-345]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:398) ~[patched_1.16.4.jar:git-Paper-345]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.4.jar:git-Paper-345]
        ... 19 more
[15:34:32 INFO]: config.yml has been loaded

**Comment by Filocava99** [comment]
The config.yml file has been corrupted due to a bug in the config serialization process.
https://hastebin.com/linepizegu.yaml
The problem has been fixed in the commit a0cb4bb5393fb3c4e29dd1304d9e7a431780afba
